class_name Enums

enum HostState { ACTIVE, ISOLATED, BEDRIDDEN }

enum TaskType {
	TEAM_TRAINING, GYM_SESSION, YOGA_STUDIO, SPA_WELLNESS, BUSINESS_TRAVEL,
	LECTURE_HALL, SORORITY_MIXER, CAMPUS_PLAZA, CHARITY_GALA, HIGH_END_DINING,
	SPONSORED_PHOTO_SHOOT, JUICE_BAR, BOARDROOM_MEETING, HIGH_STAKES_NEGOTIATION,
	LATE_NIGHT_WORK,
	SEEK_DOCTOR, PRIVATE_CLINIC, HIDE_PREGNANCY,
	REST_AND_STROKE_BELLY, PATROL_FOR_VICTIMS
}

enum TaskCategory { PHYSICAL, SOCIAL, INTELLECTUAL, INTERVENTION, OVERRIDE }

enum GestationClassType { MACROSOMIC_MULTIPLES, VANITY_CURSE, SYMBIOTIC_EPIDEMIC }

enum SkillBranch {
	SOMATIC_MALADY, ENDOCRINE_AESTHETIC_SABOTAGE, TEMPORAL_DISTORTION,
	CLASS_BRANCH_A, CLASS_BRANCH_B, CLASS_BRANCH_C,
	HOST_SELF_CARE, HOST_INVESTIGATION, HOST_MEDICAL, HOST_SOCIAL
}

enum HostArchetype { UNIVERSITY_ELITE, ADULTEROUS_TROPHY_WIFE, RUTHLESS_EXECUTIVE, FITNESS_INFLUENCER }

enum VulnerabilityType { HUMILIATION, DISCOMFORT, PREGNANCY_BRAIN, PHYSICAL_NODES }

enum GestationPhase { EARLY, MID, LATE, TERMINAL }

enum StatAffinity { PHYSICAL, MENTAL, FINANCIAL, SOCIAL }

# --- Versus mode enums ---

enum PlayerType { HUMAN, AI }

enum PlayerRole { PREGNANCY, HOST }

enum RoundPhase { DRAW, PREGNANCY_TURN, HOST_TURN, RESOLUTION }

enum CardSide { PREGNANCY, HOST }

enum SkillEffectType {
	ADD_DISCOMFORT, ADD_HUMILIATION, REDUCE_MOBILITY, REDUCE_INTELLECT,
	REDUCE_STAMINA, DRAIN_FINANCIAL, REDUCE_SOCIAL_STANDING,
	TASK_FAILURE_CHANCE, BLOCK_TASK_CATEGORY, REPLACE_TASK,
	INCREASE_GESTATION_SPEED, INCREASE_GESTATION_DENSITY, RAISE_GESTATION_CAP,
	INCREASE_BIOMASS_FROM_HUMILIATION, INCREASE_BIOMASS_FROM_DISCOMFORT,
	PASSIVE_BIOMASS_GENERATION,
	CANCEL_INTERVENTION, CONVERT_DISCOMFORT_TO_EUPHORIA, INFECTION_ZONE,
	DELETE_AUTHORITY,
	VISUAL_SWEAT, VISUAL_WARDROBE_FAILURE, VISUAL_ABDOMINAL_UNDULATION,
	VISUAL_GLOWING_VEINS, VISUAL_SKIN_TRANSLUCENT, VISUAL_PETITIFICATION,
	VISUAL_SPHERICAL_BELLY,
	# Host-side awareness effects
	RAISE_AWARENESS, REDUCE_GESTATION, BOOST_INTERVENTION,
	REDUCE_BIOMASS, SHIELD_AWARENESS
}

enum HostEffectType {
	RECOVER_AWARENESS, BLOCK_DISCOMFORT, REDUCE_GESTATION_SPEED,
	BOOST_INTERVENTION_DRIVE, REDUCE_HUMILIATION, SHIELD
}
