extends Node

# Tick timing
const SECONDS_PER_TICK := 2.0
const TICKS_PER_DAY := 12

# Win / Lose thresholds
const GESTATION_WIN_THRESHOLD := 100.0
const INTERVENTION_LOSE_THRESHOLD := 100.0

# Host AI thresholds
const BEDRIDDEN_DISCOMFORT_THRESHOLD := 85.0
const ISOLATED_HUMILIATION_THRESHOLD := 75.0
const PANIC_GESTATION_THRESHOLD := 30.0

# Biomass generation
const BASE_BIOMASS_PER_TICK := 1.0
const HUMILIATION_BIOMASS_MULT := 0.15
const DISCOMFORT_BIOMASS_MULT := 0.10

# Gestation progression
const BASE_GESTATION_PER_TICK := 0.15
const DEFAULT_GESTATION_CAP := 100.0

# Host stat decay/recovery per tick
const DISCOMFORT_NATURAL_DECAY := 0.5
const HUMILIATION_NATURAL_DECAY := 0.3
const INTERVENTION_PER_DOCTOR_VISIT := 12.0

# Task success base chances
const BASE_TASK_SUCCESS_CHANCE := 0.85
const DISCOMFORT_TASK_PENALTY_MULT := 0.005
const HUMILIATION_TASK_PENALTY_MULT := 0.004
